lib/slack_clone_web/router.ex
defmodule SlackCloneWeb.Router do
  use SlackCloneWeb, :router

  import SlackCloneWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SlackCloneWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SlackCloneWeb do
    pipe_through :browser

    live_session :chat, on_mount: SlackCloneWeb.Live.Auth do
      live "/rooms/join/:invite_code", Live.JoinRoom

      live "/", Live.IndexView
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", SlackCloneWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: SlackCloneWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", SlackCloneWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", SlackCloneWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", SlackCloneWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/slack_clone_web/controllers/user_registration_controller.ex
defmodule SlackCloneWeb.UserRegistrationController do
  use SlackCloneWeb, :controller

  alias SlackClone.Accounts
  alias SlackClone.Accounts.User
  alias SlackCloneWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :edit, &1)
          )

        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/slack_clone_web/views/user_registration_view.ex
defmodule SlackCloneWeb.UserRegistrationView do
  use SlackCloneWeb, :view
end

lib/slack_clone_web/templates/user_registration/new.html.heex
<style>
    .bg-image {
      background-image: url(https://i.postimg.cc/13pssvxG/bg-image.png);
    }
    .backdrop {
      backdrop-filter: blur(2px);
    }
  </style>

  <div class="h-screen w-full flex justify-center items-center bg-gradient-to-tr from-blue-900 to-blue-500">
    <div class="bg-image w-full sm:w-1/2 md:w-9/12 lg:w-1/2 mx-3 md:mx-5 lg:mx-0 shadow-md flex flex-col md:flex-row items-center rounded z-10 overflow-hidden bg-center bg-cover bg-blue-600">
      <div class="w-full md:w-1/2 flex flex-col justify-center items-center bg-opacity-25 bg-blue-600 backdrop">
        <h1 class="text-3xl md:text-4xl font-extrabold text-white my-2 md:my-0">
          Slack Clone
        </h1>
        <p class="mb-2 text-white hidden md:block font-mono">
          Just a slack clone app I'm doing following some tutorials
        </p>
      </div>
      <div class="w-full md:w-1/2 flex flex-col items-center bg-white py-5 md:py-8 px-4">
        <h3 class="mb-4 font-bold text-3xl flex items-center text-blue-500">
          REGISTER
        </h3>
        <.form let={f} for={@changeset} action={Routes.user_registration_path(@conn, :create)}>
          <%= if @changeset.action do %>
            <div class="alert alert-danger">
              <p>Oops, something went wrong! Please check the errors below.</p>
            </div>
          <% end %>

          <%= email_input f, :email, required: true, placeholder: "email..", class: "px-4 py-2 w-full rounded border border-gray-300 shadow-sm text-base placeholder-gray-500 placeholder-opacity-50 focus:outline-none focus:border-blue-500" %>
          <%= error_tag f, :email %>

          <%= password_input f, :password, required: true, placeholder: "password..", class: "px-4 py-2 w-full rounded border border-gray-300 shadow-sm text-base placeholder-gray-500 placeholder-opacity-50 focus:outline-none focus:border-blue-500" %>
          <%= error_tag f, :password %>

          <div class="flex justify-center items-center">
            <%= submit class: "bg-blue-500 hover:bg-blue-600 text-white focus:outline-none focus:ring rounded px-3 py-1 mt-2" do %>
              <svg class="w-5 h-5 inline"fill="none"stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1"></path>
              </svg>
              <span class="ml-1 text-lg">Register</span>
            <% end %>
          </div>
        </.form>
        <p class="text-gray-700 text-sm mt-2">
          <%= link "Log in", to: Routes.user_session_path(@conn, :new), class: "text-green-500 hover:text-green-600 mt-3 focus:outline-none font-bold underline" %> |
          <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new), class: "text-green-500 hover:text-green-600 mt-3 focus:outline-none font-bold underline" %>
        </p>
      </div>
    </div>
  </div>